# guacamole.properties

# OpenID Connect / Keycloak
openid-authorization-endpoint: http://172.21.0.12:8080/realms/project/protocol/openid-connect/auth
openid-jwks-endpoint: http://172.21.0.12:8080/realms/project/protocol/openid-connect/certs
openid-issuer: http://172.21.0.12:8080/realms/project
openid-client-id: guacamole
openid-redirect-uri: http://localhost:8088/interactive-tool/guacamole/
openid-token-endpoint: http://172.21.0.12:8080/realms/project/protocol/openid-connect/token

# Use Authorization Code Flow (NOT implicit)
openid-mode: authorization_code
#json-secret-key: babb92f2d5738f07aab087335be8b642
#json-user-mapping: /etc/guacamole/user-mapping.json